### ISSUE TITLE
Remove auto version update on lambda startup

### ISSUE THREAD

**Issue by Mor-Simplex** [newrelic/newrelic-lambda-extension#100]
## Summary
Currently we use a proxy for outbound traffic, and we allow specific domains which can be accessed for security reason. Every time that the lambda starts, it tries to pull the latest version from github.
Adding github to our whitelisted domains can result in a risk which we dont want to present.

The error is: 
`[NR_EXT] There was an issue querying for the latest agent version: Get "https://github.com/newrelic/node-newrelic/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`

## Possible Solution
Please add an environment variable to control if version pulling is required or not on lambda startup.

**Comment by kolanos** [comment]
This was addressed in #97. Let us know if you continue to have issues.
