### ISSUE TITLE
`make dist` *** No rule to make target `dist'

### ISSUE THREAD

**Issue by 4demos** [newrelic/newrelic-lambda-extension#124]
## Description
Looks like the documentation is outdated and has missing steps (may be obvious for go developers but not that much for others): `make dist`
Expected results by the docs: "This creates the extension binary in ./extensions/newrelic-lambda-extension."
Actual result: "make: *** No rule to make target `dist'. Stop."

**Comment by chaudharysaket** [comment]
Merged [PR](https://github.com/newrelic/newrelic-lambda-extension/pull/221) to update the readme
