### ISSUE TITLE
NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS requires lower-case 'true', but is documented with 'TRUE'

### ISSUE THREAD

**Issue by huonw** [newrelic/newrelic-lambda-extension#129]
## Description

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking#alt "Lambda environment variables" states:

> `NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS` | `FALSE` by default. Set to `TRUE` to send function logs to New Relic directly, bypassing CloudWatch and the newrelic-log-ingestion Lambda.

However, following those instructions literally doesn't work: it has to be `true` (lower-case), not `TRUE`.
 
## Steps to Reproduce

1. Create a lambda with the appropriate layer
2. Set `NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS=TRUE` in its environment
3. Observe subscription isn't configured correctly

## Expected Behavior

Function logs should be forwarded to new relic.

## Relevant Logs / Console output

With `NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS=TRUE`, the lambda CloudWatch logs contain:

```
LOGS Name: newrelic-lambda-extension State: Subscribed Types: [platform]
```

With `NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS=true`, they contain:

```
LOGS Name: newrelic-lambda-extension State: Subscribed Types: [platform,function]
```

## Your Environment

- Lambda: Python 3.9
- Layer: `arn:aws:lambda:ap-southeast-2:451483290750:layer:NewRelicPython39:30`

## Additional context

N/A

**Comment by maxlemieux** [comment]
Thanks for this report @huonw , this still seems to be an issue and I've submitted a fix for the docs.

**Comment by maxlemieux** [comment]
@huonw this is now fixed in docs: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda/

**Comment by maxlemieux** [comment]
@chaudharysaket this can be closed, thanks.
