### ISSUE TITLE
nodejs 14 lambda log duration over 120 seconds

### ISSUE THREAD

**Issue by xuetaofeng** [newrelic/newrelic-lambda-extension#141]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NR_NEXT] Extension shutdown after 121464ms !  And this causes our lambda timeout.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
![image](https://user-images.githubusercontent.com/64897390/210312857-0fd1ba48-8406-48be-a058-eca83385486f.png)

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
AWS nodejs 14 lambda runtime
[TIP]:  # ( Include as many relevant details about your environment as possible. )
AWS Region: eu-west-1
Nodejs14 
and Newrelic arn: arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS14X:84

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by iamemilio** [comment]
We have another similar report to this. It's a very difficult issue for us to reproduce, but we want to get to the bottom of it. We are having a hard time getting to the root cause with the information we have at the moment.

**Comment by iamemilio** [comment]
@xuetaofeng how frequently does this happen, and how frequently does your lambda function invoke? We believe this is some kind of race condition in high frequency lambda functions.

**Comment by iamemilio** [comment]
@xuetaofeng Are you setting the handler correctly? If not, this will cause a timeout. What is your handler set to?

**Comment by lucasklaassen** [comment]
@iamemilio Running into this too but can't set the handler due to using ES Modules and following the guidelines here: https://github.com/newrelic/newrelic-lambda-layers/blob/993944fd0c8b6e6592672689f22aa744bffa752c/README.md#support-for-es-modules-nodejs

Any advice?

**Comment by lucasklaassen** [comment]
@xuetaofeng are you using the `pg` postgres library?

**Comment by Arindom01** [comment]
Running into the same issue with Node14.x and pg + MiddyJS setup. Is there an example on how to handle lambda code with pg and middy library?

**Comment by chaudharysaket** [comment]
Now, `Nodejs 14` is not supported layer. Please use the latest runtime. Thank you!
