### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by pjhavariotis** [newrelic/newrelic-lambda-extension#143]
## Description

I have followed ALL the instructions found in the [docs ](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry/) to install the **New Relic AWS Lambda Telemetry extension**.
Unfortunately, I could not find any related data in the **Logs** or **Metrics & events**.
I'm wondering if this issue is related to my account (should I upgrade it ???)

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

In the CloudWatch logs of the lambda, I realized the following error:
`[NR_EXT] Telemetry client response: [403 Forbidden] {}`
`[NR_EXT] Sent 0/1 New Relic payload batches with 1 log events successfully in 272.606ms (272ms to transmit 0.4kB).`
## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by mrickard** [comment]
@pjhavariotis The most frequent cause of 403 responses in this case is an unexpected value for `NEW_RELIC_LICENSE_KEY`. I'd suggest double-checking to make sure that the license key you're using is an `INGEST-LICENSE` key, and not a user API key. 

One other cause we've seen is using a US ingest key for a function that reports to the New Relic EU region. (Or the reverse.)

**Comment by pjhavariotis** [comment]
Can you please elaborate on the "using a US ingest key for a function that reports to the New Relic EU region. (Or the reverse.)"?
As far as I know, when you create an API key, you cannot see the region.

**Comment by mrickard** [comment]
@pjhavariotis You're right that keys don't display region, and that region selection isn't an option when creating a key. The difference is whether you're logged in to `one.newrelic.com` or `one.eu.newrelic.com`.

**Comment by mrickard** [comment]
@pjhavariotis Depending on how you first configured your Lambda function, you may have an AWS managed secret in your function's region that would contain the (possibly incorrect) license key secret. Check secrets manager in that region for a `NEW_RELIC_LICENSE_KEY`, and view secret value. If it was created manually, it might have the wrong key value, or it might have the wrong structure. The plaintext should look something like `{"LicenseKey":"123456789012345678901234567890"}`, where the key string is an ingest license key.

If you don't have that managed secret in the region, or if the function's execution role doesn't have access to it, then go ahead and define `NEW_RELIC_LICENSE_KEY` as an environment variable. (You could define it as an env var anyway; I believe the env var takes precedence over the managed secret.)

**Comment by pjhavariotis** [comment]
I have just checked the secrets manager and I confirm the existence of the NEW_RELIC_LICENSE_KEY . Also I confirm that the key string is an INGEST-LICENSE key.

**Comment by mrickard** [comment]
@pjhavariotis OK. If the secret has the right value, it's still possible that the function does not have permission to read the secret as part of its execution role. As a quick check, you could set the `NEW_RELIC_LICENSE_KEY` env var to the correct ingest key value and see if that resolves your 403. If it does, then the function's problem is permissions on its execution role.

If you're still getting 403s with an explicitly defined ingest license key, I'd recommend opening a ticket with GTS. (Considering that the telemetry API extension is experimental and work-in-progress, GTS can filter that to the team.)

**Comment by pjhavariotis** [comment]
@mrickard I have just checked the execution role of the lambda and the function has already the permission needed (`Allow: secretsmanager:GetSecretValue`). What process shall I follow in order to open a ticket with GTS?

**Comment by mrickard** [comment]
@pjhavariotis If you're logged into NR1, you should be able to go to https://one.newrelic.com/help-xp.

**Comment by pjhavariotis** [comment]
OK. I am able to go there. I'm trying to open a case but the only available selections are the **Explorers Hub** & **Open Source projects, issues and questions**

**Comment by mrickard** [comment]
If you don't see a **Looking for more help?** section, then you might be on the free tier. 

As a last resort, do you still get a 403 when you explicitly define `NEW_RELIC_LICENSE_KEY` as an environment variable with the ingest key as its value?

**Comment by pjhavariotis** [comment]
I followed your suggestions and defined explicitly the `NEW_RELIC_LICENSE_KEY` environment variable. Now in the CloudWatch logs there is no 403 error. On the contrary, now I can see the following error message:
`[NR_EXT] Startup check failed: There is both a AWS Secrets Manager secret and a NEW_RELIC_LICENSE_KEY environment variable set. Recommend removing the NEW_RELIC_LICENSE_KEY environment variable and using the AWS Secrets Manager secret.`

**Comment by pjhavariotis** [comment]
Finally, it seems that the 403 error is here to stay! I strongly believe that this is related to my current account plan.
Can you please verify that?

Here is the latest log output:
`2023-01-26T08:54:37.519+02:00	[NR_EXT] New Relic Lambda Extension starting up`
`2023-01-26T08:54:37.525+02:00	[NR_EXT] Using license key from environment variable`
`2023-01-26T08:54:37.527+02:00	[NR_EXT] Starting log server.`
`2023-01-26T08:54:37.651+02:00	[NR_EXT] Startup check failed: There is both a AWS Secrets Manager secret and a NEW_RELIC_LICENSE_KEY environment variable set. Recommend removing the NEW_RELIC_LICENSE_KEY environment variable and using the AWS Secrets Manager secret.
``2023-01-26T08:54:38.227+02:00	[NR_EXT] Sent 1/1 New Relic function log batches successfully in 575.994ms (573ms to transmit 0.3kB).`
`2023-01-26T08:59:41.428+02:00	[NR_EXT] Telemetry client response: [403 Forbidden] {}`
`2023-01-26T08:59:41.428+02:00	[NR_EXT] Sent 0/1 New Relic payload batches with 1 log events successfully in 259.005ms (258ms to transmit 0.4kB).`
`2023-01-26T09:05:17.300+02:00	[NR_EXT] Telemetry client response: [403 Forbidden] {}`
`2023-01-26T09:05:17.300+02:00	[NR_EXT] Sent 0/1 New Relic payload batches with 1 log events successfully in 874.769ms (874ms to transmit 0.4kB).
``2023-01-26T09:11:06.788+02:00	[NR_EXT] Telemetry client response: [403 Forbidden] {}`
`2023-01-26T09:11:06.788+02:00	[NR_EXT] Sent 0/1 New Relic payload batches with 1 log events successfully in 274.653ms (274ms to transmit 0.4kB).
``2023-01-26T09:17:32.067+02:00	[NR_EXT] Telemetry client response: [403 Forbidden] {}`
`2023-01-26T09:17:32.067+02:00	[NR_EXT] Sent 0/1 New Relic payload batches with 1 log events successfully in 290.011ms (289ms to transmit 0.4kB).`

**Comment by pjhavariotis** [comment]
It seems that I'm currently using the **current production** extension. Here is the ARN (Frankfurt):
`arn:aws:lambda:eu-central-1:451483290750:layer:NewRelicLambdaExtension:30`

**Comment by mrickard** [comment]
That particular extension is for delivering telemetry for .NET and Go Lambda functions that have instrumentation included in their deployment package. Does that match your use case? (For Node and Python, there are layers with the appropriate agent and extension included.)

I'd double-check the ReadMe on this repo for configuration instructions, rather than the docs on the work-in-progress Telemetry API extension, which has API differences. 

But the 403 is a strong suggestion that there's something wrong with the license key being used. You may want to generate a fresh ingest license key and use that value.

**Comment by chaudharysaket** [comment]
As mentioned above, response code 403 suggests that there's issue with the ingest license key used.
