### ISSUE TITLE
Node Handler check, is not handling mjs file extension

### ISSUE THREAD

**Issue by Engerim** [newrelic/newrelic-lambda-extension#145]
## Description

The node handler check is not handling the file extension for esm modules (mjs) correctly, so you always see as an error in aws lambdas, and this is misleading
`[NR_EXT] Startup check failed: Missing handler file newrelic-lambda-wrapper.handler`

## Steps to Reproduce
* have a mjs file as a handler
* the check will tell that the handler is not found as it only looks for js files

## Expected Behavior
* handle mjs files

I'm happy to provide a pr to fix this issue

**Comment by iamemilio** [comment]
This should be resolved in the more recent layers. Please update and try again.
