### ISSUE TITLE
Using deprecated agent API in python example

### ISSUE THREAD

**Issue by shunsuke6** [newrelic/newrelic-lambda-extension#151]
## Summary

It appears that add_custom_parameter is deprecated and add_custom_attribute is used.

https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/sam/python/newrelic_example_python/app.py

## Desired Behavior
Change the API used in the example

## Additional context

It's not good that the examples provide deprecations.

**Comment by umaannamalai** [comment]
Thank you for pointing this out! We will update the example to reflect the correct API.
