### ISSUE TITLE
Dotnet core 6 support for lambda

### ISSUE THREAD

**Issue by venkiit58** [newrelic/newrelic-lambda-extension#160]
From the code, it looks like the example provided works for dotnet3.1. However, AWS already deprecated it and LTS version is 6.x

Does the existing example just works? I presume so. Please revert if you think otherwise.

Thank you.

**Comment by chaudharysaket** [comment]
.NET support was released as part of [Extension v2.3.13](https://docs.newrelic.com/docs/release-notes/lambda-extension-release-notes/lambda-extension-2.3.13/). Please use dotnet layers as found [here](https://layers.newrelic-external.com/)
