### ISSUE TITLE
New Relic Extension shutting down

### ISSUE THREAD

**Issue by mbaranovski** [newrelic/newrelic-lambda-extension#166]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Primary code of my lambda processes the requests very quickly (~60ms), however the responses are not being sent back until New Relic engine times out (after 60s my configured lambda timeout). No idea why the extension shuts down.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Expected Behaviour
New Relic extension should not shut down and if it does it should have no impact on lambda sending back response even with the cost of loosing the metrics.
[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
![CleanShot 2023-08-23 at 18 38 57@2x](https://github.com/newrelic/newrelic-lambda-layers/assets/29602306/19e22083-957e-45a4-ae2e-359543304f2d)

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
AWS Lambda + New relic lambda layer(3.10:7) integration via CLI
[TIP]:  # ( Include as many relevant details about your environment as possible. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by mirackara** [comment]
Hi @mbaranovski, Could you make sure the layer you are using is the most updated one?

**Comment by iamemilio** [comment]
Can we close this?
