### ISSUE TITLE
Binary artefacts are not available for the latest release

### ISSUE THREAD

**Issue by alexeyshockov** [newrelic/newrelic-lambda-extension#184]
https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.11 does not contain compiled arm64 & x86_64 binaries, just the source code (attached automatically by Github). Previous versions all contain the compiled binaries in addition to the source code.

Please fix the release process so the binaries are back.

**Comment by chaudharysaket** [comment]
Hi, We have a new release for [v2.3.11](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.11). You can find [newrelic-lambda-extension.arm64.zip](https://github.com/newrelic/newrelic-lambda-extension/releases/download/v2.3.11/newrelic-lambda-extension.arm64.zip) and [newrelic-lambda-extension.x86_64.zip](https://github.com/newrelic/newrelic-lambda-extension/releases/download/v2.3.11/newrelic-lambda-extension.x86_64.zip) binaries. Thanks
