### ISSUE TITLE
GO SAM sample logging errors

### ISSUE THREAD

**Issue by brucemackenzie** [newrelic/newrelic-lambda-extension#185]
[NOTE]: # /var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.34' not found 

## Description
Seeing /var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /var/task/bootstrap)  in aws cloudwatch logs.

## Steps to Reproduce
1. build the example.
2. send it a test message.

## Expected Behavior
No errors.

## Relevant Logs / Console output
[NR_EXT] New Relic Lambda Extension starting up
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /var/task/bootstrap)
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /var/task/bootstrap)
EXTENSION	Name: newrelic-lambda-extension	State: Registered	Events: [INVOKE, SHUTDOWN]
INIT_REPORT Init Duration: 86.89 ms	Phase: init	Status: error	Error Type: Runtime.ExitError

## Your Environment
aws

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by imphatic** [comment]
Hi!  +1 this issue is taking down our whole app.  
`
/opt/extensions/newrelic-lambda-extension: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /opt/extensions/newrelic-lambda-extension)`

**Comment by chaudharysaket** [comment]
The `GLIBC_2.34` error was result of migration of CI pipeline. Any of the production layers don't have such issue. Please use [latest layer](https://layers.newrelic-external.com/) for the lambda runtime.
