### ISSUE TITLE
NEW_RELIC_LICENSE_KEY in different region on AWS Secrets Manager

### ISSUE THREAD

**Issue by manufunk** [newrelic/newrelic-lambda-extension#208]
## Description

I discovered that if the secret of the NEW_RELIC_LICENSE_KEY is not in the same region, this will cause problems as the layer is not able to find the secret and I get the following error:

```
[NR_EXT] Failed to retrieve New Relic license key No license key configured
```

I then tried to work around it by looking in the extension code and found the env variable `NEW_RELIC_LICENSE_KEY_SECRET`. So I placed my secret arn inside it. However this ended up in the following message:

```
[NR_EXT] Failed to retrieve New Relic license key ResourceNotFoundException: Secrets Manager can't find the specified secret.
```

The secret is there in the specified arn however I guess the region is ignored.

## Steps to Reproduce

Create a sample and place the secret in a different region and point to it.

## Expected Behavior

The secret should be pulled from the different region.

## Relevant Logs / Console output

Mentioned in the description already

## Your Environment

Nodejs with AWS node 18 and respective layer

**Comment by chaudharysaket** [comment]
We will work on this issue.

**Comment by chaudharysaket** [comment]
After conducting an analysis, we find that retrieving secrets from a cross-region Secrets Manager can introduce latency exceeding 1 second to the invocation `Duration`. We recommend utilising the Secrets Manager in the same region as the Lambda function or storing the License Key as a Lambda environment variable `NEW_RELIC_LICENSE_KEY`.
