### ISSUE TITLE
`layer:NewRelicNodeJS18X:84` lost request request.method, request.uri in AwsLambdaInvocation

### ISSUE THREAD

**Issue by Blankll** [newrelic/newrelic-lambda-extension#232]
## Description
we have a lambda using NewRelicNodeJS18X to integrate newrelic for observability, it all looks good until version 84,  we lost the value of fields:  `request.method`, `request.uri`, and  user-customized request headers are not shown in the record anymore

## Steps to Reproduce
1. setup lambda with `@vendia/serverless-express` to handler request,
2.  add layer `arn:aws:lambda:ap-southeast-2:451483290750:layer:NewRelicNodeJS18X:84`
3. set lambda env to config newrelic passing all headers: NEW_RELIC_ALLOW_ALL_HEADERS: true

however, headers are not have value in AwsLambdaInvocation record

## Expected Behavior
`request.method`, `request.uri`, and  user-customized request headers should have values on `AwsLambdaInvocation` like version before 84
## Your Environment
lambda runtime: Node.js 18.x
layers: arn:aws:lambda:ap-southeast-2:451483290750:layer:NewRelicNodeJS18X:84
arch: x86_64

## Additional context
headers fields are sent correctly in version 83

**Comment by chaudharysaket** [comment]
Thank you for bringing this to our attention. We are investigating the issue.

**Comment by chaudharysaket** [comment]
Hi @Blankll 
We have [released](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v12.3.1.0_nodejs) layers with node agent [v12.3.1](https://github.com/newrelic/node-newrelic/releases/tag/v12.3.1).

Please let us know if you still face issue related to missing `request.uri` & `request.method` with the latest layer - `arn:aws:lambda:ap-southeast-2:451483290750:layer:NewRelicNodeJS18X:85`

Thank you!
