### ISSUE TITLE
Dead link in Support section of README

### ISSUE THREAD

**Issue by elazar** [newrelic/newrelic-lambda-extension#33]
In the [Support section of the README](https://github.com/newrelic/newrelic-lambda-extension#support), the text "in the Explorers Hub" is linked with the following URL:

https://discuss.newrelic.com/t/new-relic-lambda-extension/111715

When I visit this URL, despite being logged in, I get the following error:

> Sorry, you don't have access to that topic!

I am however able to access other threads, such as this one.

https://discuss.newrelic.com/t/problems-setting-up-serverless-monitoring-lambda-layer/122424

Is it possible the thread linked in the README no longer exists?

**Comment by MattWhelan** [comment]
Thanks, @elazar! That's an oversight on our part. We created that topic as internal only before we released, and it looks like we forgot to make it public. I'll make sure that gets taken care of.

**Comment by MattWhelan** [comment]
Ok, that should be fixed now. That topic is no longer internal-only.
