### ISSUE TITLE
terraform examples issue with policy arn

### ISSUE THREAD

**Issue by dpinol** [newrelic/newrelic-lambda-extension#46]
## Description

When deploying python or node from examples/terraform/, I get "The argument "policy_arn" is required, but no definition was found."

## Steps to Reproduce

```
cd examples/terraform/python #or node
terraform init
./deploy.sh MY_ACCOUNT_ID eu-west-1
```

## Expected Behavior

A new lambda is deployed

## Relevant Logs / Console output
```

region set to eu-west-1
Success! The configuration is valid.

data.aws_caller_identity.current: Refreshing state...
data.aws_iam_policy.newrelic_license_key_policy: Refreshing state...

Error: Missing required argument

  on main.tf line 24, in resource "aws_iam_role_policy_attachment" "newrelic_license_key_policy_attachment":
  24:   policy_arn = data.aws_iam_policy.newrelic_license_key_policy.arn

The argument "policy_arn" is required, but no definition was found.
```

## Your Environment

* linux mint 20.1
* terraform: v0.14.6 (provider.aws v3.27.0). Also tested with v0.12.28
* 
## Additional context

I tried hardcoding  policy_arn inline 24,
`policy_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/ViewNewRelicLicenseKey"
`
but then I got this error
```
Error: Error attaching policy arn:aws:iam::XXXXX:policy/ViewNewRelicLicenseKey to IAM Role newrelic_terraform_example_nodejs_role: NoSuchEntity: Policy arn:aws:iam::XXXXX:policy/ViewNewRelicLicenseKey does not exist or is not attachable.
	status code: 404, request id: XXXXX
```

Not related, but I guess that .terraform.lock.hcl shouldn't be in github right?

thanks

**Comment by kolanos** [comment]
@dpinol Thanks for reporting. Did you create the license key secret in your AWS account using the CLI? This is one of the prerequisites covered in the README.

**Comment by kolanos** [comment]
The relevant section of the README:

> Make sure you've run the `newrelic-lambda install` command in your
AWS Region, and included the `--enable-license-key-secret` flag.

Terraform should be able to find the policy ARN after running that command on your AWS account.

**Comment by kolanos** [comment]
@dpinol Closing this for now. Please feel free to re-open if you're still having issues. Thanks.
