### ISSUE TITLE
License key sanity check isn't

### ISSUE THREAD

**Issue by dpiddock** [newrelic/newrelic-lambda-extension#54]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
Erroneous message from the sanity check added in #36 when passing the license key as an environment variable.

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
I am manually adding the Python layer to a test function, passing the license key in as an environment variable. There is a message in the log on every cold start about how I should remove the environment variable because a Secrets Manager secret is also present. There is no Secrets Manager secret.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
1. Do not have a Secrets Manager secret containing the newrelic key
2. Pass New Relic license key in `NEW_RELIC_LICENSE_KEY` environment variable on the lambda
3. Invoke the lambda
4. Check logs for
   > [NR_EXT] Startup check failed: There is both a AWS Secrets Manager secret and a NEW_RELIC_LICENSE_KEY environment variable set. Recommend removing the NEW_RELIC_LICENSE_KEY environment variable and using the AWS Secrets Manager secret.

## Expected Behavior

No warning message in the log about duplicate key provisioning.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
> [NR_EXT] Startup check failed: There is both a AWS Secrets Manager secret and a NEW_RELIC_LICENSE_KEY environment variable set. Recommend removing the NEW_RELIC_LICENSE_KEY environment variable and using the AWS Secrets Manager secret.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
- Python 3.8 lambda
- layer:NewRelicPython38:33

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

#36 added a sanity check for the license key. It does this by checking for the presence of the environment variable `NEW_RELIC_LICENSE_KEY` and by also calling `credentials.GetLicenseKeyImpl()` [(here)](https://github.com/newrelic/newrelic-lambda-extension/blob/40b0aab0607cd315307fc0120a5656363ecd83c2/checks/sanity_check.go#L37). 

`GetLicenseKeyImpl()` itself falls back to returning the value in the environment variable if it is present and fetching from Secrets Manager failed [(here)](https://github.com/newrelic/newrelic-lambda-extension/blob/40b0aab0607cd315307fc0120a5656363ecd83c2/credentials/credentials.go#L51). 

The sanity check is not achieving what it aimed to do.

**Comment by MattWhelan** [comment]
I agree that this is a bug. We'll address this in a future release of the extension.

In the meantime, you can disregard that message; the startup checks are advisory only, and this bug shouldn't otherwise impair the function of the extension.
