### ISSUE TITLE
Readme appears to incorrectly state Extension is disabled by default

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/newrelic-lambda-extension#56]
Readme file statement:

> The New Relic Lambda Extension is disabled by default. To enable it, after adding or updating the Lambda layer, set the NEW_RELIC_LAMBDA_EXTENSION_ENABLED environment variable to any value.

However code block appears to show enabled-by-default:
```
enabledStr, extensionEnabledOverride := os.LookupEnv("NEW_RELIC_LAMBDA_EXTENSION_ENABLED")

extensionEnabled := true
if extensionEnabledOverride && "false" == strings.ToLower(enabledStr) {
    extensionEnabled = false
}
```

https://github.com/newrelic/newrelic-lambda-extension/blob/d243e521d6a7050c6a5bacc513c5a620dd8e57d1/config/config.go#L31

**Comment by kolanos** [comment]
@GaPeppy Thanks for reporting. Originally the extension was disabled by default. Looks like the README was not updated to reflect the new default.
