### ISSUE TITLE
New Relic Layer errors randomly

### ISSUE THREAD

**Issue by colm-madigan** [newrelic/newrelic-lambda-extension#66]
## Description

Our kotlin Lambdas are producing error logs when running through the New Relic layer which are spamming our alert notifications. The logs provide no other details other than a Lambda runtime failure.
These only started appearing after integrating the layer and stopped when the layer was removed. 

## Steps to Reproduce

Intermittently happens after an unknown amount of time.

## Expected Behavior

Does not cause the [ERROR] in the Lambda logs

## Relevant Logs / Console output

    | 1619106082000 | [NR_EXT] New Relic Lambda Extension starting up
    | 1619106082210 | [NR_EXT] Starting log server.
    | 1619106082212 | LOGS Name: newrelic-lambda-extension State: Subscribed Types: [platform,function]
    | 1619106088310 | [2021-04-22 15:41:27.295] " + NO_REQUEST_ID + " INFO c.a.i.DefaultServiceEndpointBuilder - {rds-data, eu-west-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'rds-data.eu-west-1.amazonaws.com'.
    | 1619106089032 | [NR_EXT] Sent 1/1 New Relic function log batches successfully in 216.247ms (214ms to transmit 0.4kB).
    | 1619106090709 | EXTENSION Name: newrelic-lambda-extension State: Ready Events: [INVOKE,SHUTDOWN]
    | 1619109040622 | [ERROR] [1619109040622] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint
    | 1619109040627 | [NR_EXT] New Relic Extension shutting down after 1 events
    | 1619109040828 | [NR_EXT] Extension shutdown after 2958806ms

## Your Environment

Runtime: Java 11 (Cornetto)
AWS Lambda core version: 1.2.1
Handler: Implementation of the RequestHandler

## Additional details

This happened when using both the NewRelicJava11:1 and NewRelicLambdaExtension:11 layers

**Comment by kolanos** [comment]
@colm-madigan Thanks for the report. We have released a refactor of our timeout logic which should (hopefully) do the right thing in most cases. We hope you'll give it a try and report any issues you run into.

**Comment by kolanos** [comment]
@colm-madigan Closing this for now. Please feel free to re-open if you continue to see this error with this extension. Thanks again.
