### ISSUE TITLE
Use fixed port in the logsever

### ISSUE THREAD

**Issue by luben** [newrelic/newrelic-lambda-extension#71]
https://github.com/newrelic/newrelic-lambda-extension/blob/fcdd844641bb4628154277198c3f12177404ad34/lambda/logserver/logserver.go#L156

If log server starts listening on random port, and Lambda sandbox (function and extensions) is restarted, it can lose logs from the previous invocation or the log server could receive duplicate logs. Using a stable port in the same sandbox will guarantee exactly-once delivery of the logs. It also will reduce the memory utilization in the sandbox.

**Comment by kolanos** [comment]
@luben Thanks for the heads up. Is this behavior documented anywhere? Also, are there any guidelines for port numbers to avoid conflicts with other extensions?

**Comment by luben** [comment]
Hi, sorry I missed the question.

You can use any port != 9001. It's documented in https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html#runtimes-logs-api-dest

Though this may cause conflict with other extensions. May be try some static port and if the bind fails fall-back to random.

Unfortunately this behaviour around guarantees is not documented.

**Comment by kolanos** [comment]
Static port added in #77.
