### ISSUE TITLE
Golang Layer example fails silently for older versions of aws-lambda-go

### ISSUE THREAD

**Issue by daniel-toye-vt** [newrelic/newrelic-lambda-extension#78]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The example at newrelic-lambda-extension/examples/sam/go has a silent failure if the aws-lambda-go version is pre-1.18. One service I was working on had been built at a time when v1.13 was the latest version, and pinned since then.

The example instructs using `-tags lambda.norpc` but that build tag will have no effect if using a pre-1.18 version of the lambda package, and is a difficult error to track down - it results in mysterious timeouts after successfully running the cold start of a lambda, due to rpc server blocking the main thread.

## Steps to Reproduce

Attempt to deploy this lambda after having checked out a version before 

https://github.com/aws/aws-lambda-go/releases/tag/v1.18.0

Custom Runtime support is listed as a feature change in that version.

## Expected Behavior

Golang does not emit any warnings in this situation, so a warning in this example would be appropriate.

**Comment by kolanos** [comment]
@daniel-toye-vt Thank you for reporting this issue. We'll make sure this version compatibility is in the README for that example.
