### ISSUE TITLE
The description about command "newrelic-lambda" can be updated

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/newrelic-lambda-extension#85]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
The description about command "newrelic-lambda" can be updated in the following README file;
https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/sam/go/README.md#prerequisites

Today it is described as following;
> Make sure you've run the newrelic-lambda install command in your AWS Region, and included the --enable-license-key-secret flag.

However `newrelic-lambda install` doesn't work today and it should be `newrelic-lambda integrations install` and flag `--enable-license-key-secret` is replaced new flag `--disable-license-key-secret`

## Steps to Reproduce
n/a

## Expected Behavior
n/a

## Relevant Logs / Console output
n/a

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

**Comment by chaudharysaket** [comment]
This issue was fixed [here](https://github.com/newrelic/newrelic-lambda-extension/pull/103)
