### ISSUE TITLE
Node.js missing invocations

### ISSUE THREAD

**Issue by navihtot** [newrelic/newrelic-lambda-extension#89]
## Description

On regular basis some invocations are missing on New Relic, but clearly can be found on CloudWatch.

## Steps to Reproduce
Hard to say. Every time couple of invocations are missing. For example if invoked 20 times it'll miss 2-3 invocations - it seems as last couple of invocations.

## Expected Behavior
Having all invocation

## Your Environment
- node.js 14 with TypeScript
- Using New Relic serverless plugin https://github.com/newrelic/serverless-newrelic-lambda-layers
- cloudwatch ingest function is removed

**Comment by kolanos** [comment]
This should be fixed in #101. Let us know if you continue to see this issue after upgrading.
