### ISSUE TITLE
Missing logs when function times out

### ISSUE THREAD

**Issue by JCapriotti** [newrelic/newrelic-lambda-extension#91]
## Description

We have a lambda function that occasionally hits the 15-minute mark and times out. I noticed that no logs (errors or otherwise) show up in New Relic for these scenarios. 

## Steps to Reproduce

Based on our logs:
1. Get a Lambda to run over 15 minutes using Python 3.8 and the layer ARN `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicPython38:51`
2. Find the CloudWatch logs for the logs, specifically the `RequestId`
3. Look for the logs in New Relic and the `RequestId` above is missing.

## Expected Behavior

1. The `RequestId` shows up in New Relic logs
2. New Relic reports an error

### CloudWatch Log Insight query: 
```
fields @timestamp, @requestId, @message
| filter @message like /(NR_EXT|START RequestId|REPORT|timed out)/
| sort @timestamp 
```
[logs-insights-results.csv](https://github.com/newrelic/newrelic-lambda-extension/files/7449124/logs-insights-results.csv)
The request that timed out was id `e1a4b364-e0f5-4a27-a1dc-44a736937370`

### New Relic AwsLambdaInvocation query:

```
select timestamp, aws.requestId, duration  
from AwsLambdaInvocation 
where entityName = 'xyz' SINCE 3 days ago
```
|Timestamp          |Aws.Request ID                      |Duration          |
|-------------------|------------------------------------|------------------|
|2021-10-29 13:22:25|c4e43c76-28de-4a78-8e95-43a695a91acd|791.6913824081421 |
|2021-10-29 08:00:21|d8989ab2-a7e1-4abc-9f31-79480bf26467|49.77254390716553 |
|2021-10-29 08:00:21|e5e0c7b2-9227-461e-83ce-c2db21b9dc2b|701.8979961872101 |
|2021-10-29 08:00:21|63d224c4-112a-4f6f-aeda-fbea2b288a2c|178.43485140800476|
|2021-10-29 08:00:20|3d7059b0-3caf-45de-abb6-9befee05eea1|18.820170879364014|

### New Relic ServerlessSample query:
```
select timestamp, provider.errors.Sum, provider.duration.Maximum, provider.invocations.Sum 
from ServerlessSample 
where entityName = 'xyz' SINCE 3 days ago until 2 days ago
```

| timestamp | provider.errors.sum |  provider.duration.maximum |  provider.invocations.sum
|------------------------------|--------------|-----|-----|
 |October 29, 2021 08:22:00   |  | | |
| October 29, 2021 03:00:00   | 0 | 178677.11 | 3 |

***NOTE:*** I noticed in the `ServerlessSample` query results above, in addition to missing the timeout, it does not seem to include data for the RequestId `e5e0c7b2-9227-461e-83ce-c2db21b9dc2b`. Not counting the timeout, I would expect the second row to show something like:
* `provider.duration.maximum` =  701897
* `provider.invocations.sum` = 4

## Your Environment

* Lambda Runtime: Python 3.8
* Layer ARN: arn:aws:lambda:us-east-1:451483290750:layer:NewRelicPython38:51 
  * Should have been latest as of our last release, on 2021-10-10

**Comment by kolanos** [comment]
This should be fixed in #101. Let us know if you are continuing to see this issue after upgrading.
