### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [newrelic/newrelic-lambda-extension#99]
https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/terraform/nodejs/README.md is out of date
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
While trying to implement the example found in https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/terraform/nodejs I noticed that the instructions are out of date. 

1. The instructions refer to running `newrelic-lambda install`, but I believe the correct command is `newrelic-lambda integrations install` and it does not look like `--enable-license-key-secret` flag is still valid.
2. Inside main.tf 
```
data "aws_iam_policy" "newrelic_license_key_policy" {
  arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/ViewNewRelicLicenseKey"
}
```
throws an error since the policy created by the step in #1 has a different name.

There may be other problems and it would be great to get them fixed.

**Comment by chaudharysaket** [comment]
This issue was fixed [here](https://github.com/newrelic/newrelic-lambda-extension/pull/103)
